version: "3.9"

services:
  postgres_simulation:
    container_name: at_simulation_db
    image: "postgres:alpine"
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"  
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    restart: unless-stopped
    networks:
      - custom-network
    healthcheck:
      test: pg_isready --dbname=${DB_NAME} --username=${DB_USER} --host=localhost --port=${DB_PORT}
      interval: 10s  
      timeout: 5s
      retries: 10 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "port=${DB_PORT}"]

  minio:
    container_name: at_minio
    image: "minio/minio:latest"
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}" --address ":${MINIO_API_PORT}"
    ports:
      - "${MINIO_API_PORT}:${MINIO_API_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    restart: unless-stopped
    networks:
      - custom-network

networks:
  custom-network:
    external: true

volumes:
  postgres-data:
  minio-data:
